# File: carrental-pr.yaml
# Description: Build Validation Pipeline used for Pull Requests.

trigger: none

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"

steps:
  - script: dotnet build ./CarRental --configuration $(buildConfiguration)
    displayName: "Build the project"
  - script: dotnet test ./CarRental
    displayName: "Run tests"
