using Ardalis.Result;
using Ardalis.Specification;
using AutoMapper;
using CarRental.Common.Core.Enums;
using CarRental.Common.Core.ProviderEntities;
using CarRental.Provider.API.DTOs.Rentals;
using CarRental.Provider.API.Requests.Rentals.Commands;
using CarRental.Provider.Infrastructure.EmailServices;
using CarRental.Provider.Persistence.Specifications.Rentals;
using MediatR;

namespace CarRental.Provider.API.Requests.Rentals.Handlers;

public class ReturnRentalCommandHandler : IRequestHandler<ReturnRentalCommand, Result<RentalStatusDto>>
{
    private readonly IRepositoryBase<Rental> rentalsRepository;
    private readonly IMapper mapper;
    private readonly IEmailInputMaker emailInputMaker;

    public ReturnRentalCommandHandler(
        IRepositoryBase<Rental> rentalsRepository,
        IMapper mapper,
        IEmailInputMaker emailInputMaker,
        IEmailService emailService)
    {
        this.rentalsRepository = rentalsRepository;
        this.mapper = mapper;
        this.emailInputMaker = emailInputMaker;
    }

    public async Task<Result<RentalStatusDto>> Handle(ReturnRentalCommand request, CancellationToken cancellationToken)
    {
        var specification = new RentalByIdWithOfferCarModelMakeClientSpecification(request.Id);

        var rental = await this.rentalsRepository.FirstOrDefaultAsync(specification, cancellationToken);

        if (rental == null)
        {
            return Result<RentalStatusDto>.NotFound();
        }

        if(rental.Offer.GeneratedBy != request.Audience)
        {
            return Result<RentalStatusDto>.Forbidden("Offer associated with rental was generated by a different audience.");
        }

        if (rental.Status == RentalStatus.ReadyForReturn)
        {
            return Result<RentalStatusDto>.Success(this.mapper.Map<RentalStatusDto>(rental));
        }

        if (rental.Status != RentalStatus.Active)
        {
            return Result<RentalStatusDto>.Invalid(
                    new ValidationError(nameof(Rental.Status), $"Rental is not in the {nameof(RentalStatus.Active)} state.")
                );
        }

        rental.Status = RentalStatus.ReadyForReturn;

        await this.rentalsRepository.UpdateAsync(rental, cancellationToken);
        await this.rentalsRepository.SaveChangesAsync(cancellationToken);

        var input = emailInputMaker.GenerateRentalReturnStartedTemplate(
            rental.Customer.EmailAddress,
            $"{rental.Customer.FirstName} {rental.Customer.LastName}",
            rental.Offer.Car.Model.Make.Name,
            rental.Offer.Car.Model.Name);

        var rentalStatusDto = this.mapper.Map<RentalStatusDto>(rental);

        return Result<RentalStatusDto>.Success(rentalStatusDto);
    }
}